variables:
  GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
  CI_REGISTRY_IMAGE: $REGISTRY/$REGISTRY_PROJECT
  CI_IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME

before_script:
  - echo $GCLOUD_SERVICE_KEY | base64 -d >$GOOGLE_APPLICATION_CREDENTIALS
  - docker login -u _json_key -p "$(cat $GOOGLE_APPLICATION_CREDENTIALS)" https://$REGISTRY

image: docker:1.11

stages:
  - build
  - release

build:
  stage: build
  script:
    - docker build --pull -t $CI_IMAGE_TAG:$CI_BUILD_REF .
    - docker push $CI_IMAGE_TAG:$CI_BUILD_REF
  except: 
    - tags

release-by-name:
  stage: release
  script: 
    - docker pull $CI_IMAGE_TAG:$CI_BUILD_REF
    - docker tag $CI_IMAGE_TAG:$CI_BUILD_REF $CI_IMAGE_TAG:$CI_BUILD_REF_NAME
    - docker push $CI_IMAGE_TAG:$CI_BUILD_REF_NAME
  except: 
    - master

release-master:
  stage: release
  script: 
    - docker pull $CI_IMAGE_TAG:$CI_BUILD_REF
    - docker tag $CI_IMAGE_TAG:$CI_BUILD_REF $CI_IMAGE_TAG:latest
    - docker push $CI_IMAGE_TAG:latest
  only: 
    - master
